### ISSUE TITLE
Missing Plex and TMDB Info, Seer causing an error

### ISSUE THREAD

**Issue by iamronr** [Vansmak/mediarr-card#1]
I'm not sure what I'm missing at the moment. TMDB API is definitely working, because it's pulling posters. For whatever reason, I can't get the content for Plex and TMDB to appear. I'm currently running the latest (released today) card and sensor. I'm also getting a seer error in logs in Home Assistant, which is causing the card to not work until I comment it out in my sensors.yaml. I have reinstalled both, and cleared cache in my browser.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/mediarr/sensor.py", line 86, in async_setup_platform
    config["seer"]["api_key"],
    ~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'api_key'
```

My sensors.yaml
```
 - platform: mediarr
    plex:
      host: 192.168.100.65
      port: 32400
      token: !secret plex_token
      max_items: 10
      tmdb_api_key: !secret tmdb_api_long_key
    
    #seer:
    #  url: http://192.168.100.65:5055
    #  token: !secret jellyseerr_api
    #  max_items: 10
    #  tmdb_api_key: !secret tmdb_api_long_key
    
    sonarr:
      url: http://192.168.100.65:8989
      api_key: !secret sonarr_api
      max_items: 10
      days_to_check: 30
      tmdb_api_key: !secret tmdb_api_long_key
    
    radarr:
      url: http://192.168.100.65:7878
      api_key: !secret radarr_api
      max_items: 10
      tmdb_api_key: !secret tmdb_api_long_key

    trakt:
      client_id: !secret trakt_client_id
      client_secret: !secret trakt_client_secret
      tmdb_api_key: !secret tmdb_api_long_key
      trending_type: both  # Options: movies, shows, both
      max_items: 10

    tmdb:
      api_key: !secret tmdb_api_long_key
      trending_type: all  # Options: movie, tv, all
      max_items: 10
      trending: true
      now_playing: true
      upcoming: true
      on_air: true
      airing_today: true
```

The card on my dashboard
```
type: custom:mediarr-card
plex_entity: sensor.plex_mediarr
radarr_entity: sensor.radarr_mediarr
sonarr_entity: sensor.sonarr_mediarr
seer_entity: sensor.seer_mediarr
trakt_entity: sensor.trakt_mediarr
tmdb_entity: sensor.tmdb_mediarr
tmdb_now_playing_entity: sensor.tmdb_mediarr_now_playing
tmdb_upcoming_entity: sensor.tmdb_mediarr_upcoming
tmdb_on_air_entity: sensor.tmdb_mediarr_on_air
opacity: 0.7
blur_radius: 0

```

![Image](https://github.com/user-attachments/assets/0b23046c-456e-4b7d-9e07-60aa6707f6e3)

**Comment by iamronr** [comment]
For the record, I really appreciate the work you've been putting in. This looks amazing! My goal is to get my config right so I can assist where I can with those that need help. And If I can spot bugs, report them as needed.

**Comment by Para96** [comment]
I had the same problem, the documentation on the front page is incorrect 
It is not "token" but "api_key" for seer

**Comment by Vansmak** [comment]
Most people know it's pretty much the same thing. Sorry I made an errarr in the readme. There will be many more I'm sure

**Comment by Vansmak** [comment]
Yes the label may say token for Plex jelly and seer but for jf and seer use the API key. Only Plex used a token. Most people know it's pretty much the same thing. 

I'll fix the readme. So sorry for the errarr.

**Comment by iamronr** [comment]
I updated Seer to api_key, that error went away. Here are the two new errors I'm seeing:

```
This error originated from a custom integration.

Logger: custom_components.mediarr.discovery.tmdb
Source: custom_components/mediarr/discovery/tmdb.py:72
integration: Mediarr (documentation, issues)
First occurred: 7:46:55 AM (10 occurrences)
Last logged: 7:47:37 AM

Error updating TMDB sensor: Failed to fetch TMDB now_playing. Status: 401
Error updating TMDB sensor: Failed to fetch TMDB upcoming. Status: 401
Error updating TMDB sensor: Failed to fetch TMDB trending. Status: 401
Error updating TMDB sensor: Failed to fetch TMDB on_air. Status: 401
Error updating TMDB sensor: Failed to fetch TMDB airing_today. Status: 401
```

and

```
This error originated from a custom integration.

Logger: custom_components.mediarr.discovery.seer
Source: custom_components/mediarr/discovery/seer.py:158
integration: Mediarr (documentation, issues)
First occurred: 7:46:55 AM (2 occurrences)
Last logged: 7:47:37 AM

Error updating Jellyseerr/Overseerr sensor: Failed to connect to Jellyseerr/Overseerr. Status: 403
```

Here's my current sensors.yaml:

```
- platform: mediarr
    plex:
      host: 192.168.100.65
      port: 32400
      token: !secret plex_token
      max_items: 10
      tmdb_api_key: !secret tmdb_api_long_key
    
    seer:
      url: http://192.168.100.65:5055
      api_key: !secret jellyseerr_api
      max_items: 10
      tmdb_api_key: !secret tmdb_api_long_key
    
    sonarr:
      url: http://192.168.100.65:8989
      api_key: !secret sonarr_api
      max_items: 10
      days_to_check: 30
      tmdb_api_key: !secret tmdb_api_long_key
    
    radarr:
      url: http://192.168.100.65:7878
      api_key: !secret radarr_api
      max_items: 10
      tmdb_api_key: !secret tmdb_api_long_key

    trakt:
      client_id: !secret trakt_client_id
      client_secret: !secret trakt_client_secret
      tmdb_api_key: !secret tmdb_api_long_key
      trending_type: both  # Options: movies, shows, both
      max_items: 10

    tmdb:
      api_key: !secret tmdb_api_long_key
      trending_type: all  # Options: movie, tv, all
      max_items: 10
      trending: true
      now_playing: true
      upcoming: true
      on_air: true
      airing_today: true

```
