### ISSUE TITLE
Some sections show no content and broken images in Trending/Discover, and dark movie banners cause text visibility issues

### ISSUE THREAD

**Issue by BMWfan** [Vansmak/mediarr-card#11]
Hi,
first of all – thank you for this card! I really like the concept and design.

However, I’m encountering a couple of issues:

1. **Empty Sections**: Some of the sections (e.g. `[RADARR, TRENDING on TMDB, PLEX RECENTLY ADDED ]`) show no content at all, even after refreshing or reloading Home Assistant.
2. **Broken Images**: In the "Trending" and "Discover" sections, several movies show broken thumbnails or image placeholders instead of posters.
3. **Text Visibility with Dark Banners**: When clicking on a movie that has a dark banner/background, the entire card adopts this color scheme — which causes the section titles or labels to become unreadable due to low contrast. It would be great if the text color could adapt dynamically to the banner brightness or background (e.g., using light text on dark banners).

![Image](https://github.com/user-attachments/assets/e51d0a57-4e2b-4ada-b603-6393da49ace8)

![Image](https://github.com/user-attachments/assets/5330a23b-4ba8-4af3-8009-7f0e7e14a1fb)

**Sensor configuration:**

  ```
- platform: mediarr
    radarr:
      url: http://radarr:7878
      api_key: !secret radarr_apikey
      max_items: 10
      days_to_check: 60
      tmdb_api_key: !secret tmdb_apikey_long

    tmdb:
      tmdb_api_key: !secret tmdb_apikey_long
      trending_type: all  # Options: movie, tv, all
      max_items: 10
      trending: true          # Default endpoint
      now_playing: true       # Optional
      upcoming: true          # Optional
      on_air: true            # Optional
      airing_today: false     # Optional
      popular_movies: true
      popular_tv: true

    sonarr:
      url: http://sonarr:8989
      api_key: !secret sonarr_apikey
      max_items: 45
      days_to_check: 60

    plex:
      url: 192.168.178.100
      token: !secret plex_token
      max_items: 45
      tmdb_api_key: !secret tmdb_apikey_long
      language: de

    seer:
      url: http://overseerr:5055
      api_key: !secret seer_apikey
      max_items: 45  #example how many items you want in sensor, you can chosse a different amount in card
      tmdb_api_key: !secret tmdb_apikey_long
      trending: true # Optional
      discover: true  # Optional
      popular_movies: false  # Optional, recommended to use tmdb for popular
      popular_tv: false # Optional, recommended to use tmdb for popular
```

**Mediarr Card configuration:**

```
type: custom:mediarr-card
media_player_entity: media_player.fire_tv_192_168_178_50
sonarr_entity: sensor.sonarr_mediarr
sonarr_label: sonarr
radarr_entity: sensor.radarr_mediarr
radarr_label: radarr
radarr_release_types:
  - Digital
  - Theatres
  - Physical
tmdb_entity: sensor.tmdb_mediarr
plex_entity: sensor.plex_mediarr
seer_entity: sensor.seer_mediarr
seer_trending_entity: sensor.seer_mediarr_trending
seer_discover_entity: sensor.seer_mediarr_discover
max_items: 15
days_to_check: 360
opacity: 0.7
blur_radius: 5
```

**What I’ve tried:**

* Reloading the card and clearing the browser cache
* Verifying my API connection and configuration
* Testing with different themes and devices

**Possible related Logs:**
```
2025-05-08 10:40:20.676 WARNING (MainThread) [custom_components.mediarr.discovery.seer_discovery] No items passed filters for trending, using fallback
2025-05-08 10:40:20.749 WARNING (MainThread) [custom_components.mediarr.discovery.seer_discovery] No items passed filters for discover, using fallback
2025-05-08 10:40:50.713 WARNING (MainThread) [custom_components.mediarr.discovery.seer_discovery] No items passed filters for trending, using fallback
2025-05-08 10:40:50.832 WARNING (MainThread) [custom_components.mediarr.discovery.seer_discovery] No items passed filters for discover, using fallback
```

If any additional logs or debug info would help, I’m happy to provide that.

Thanks in advance for taking a look!
