### ISSUE TITLE
Don't get the connection to Plex and TMDB

### ISSUE THREAD

**Issue by dataanh** [Vansmak/mediarr-card#5]
Hello,
i downloaded the updated version and tried several things, but i don't get my mistake.
Logs say.
`Error initializing Plex sensors: 'url'`
`Error updating Jellyseerr/Overseerr sensor:`
`Error updating TMDB sensor: Failed to fetch TMDB now_playing. Status: 401
Error updating TMDB sensor: Failed to fetch TMDB on_air. Status: 401
Error updating TMDB sensor: Failed to fetch TMDB trending. Status: 401
Error updating TMDB sensor: Failed to fetch TMDB upcoming. Status: 401`

Here ist my config:
`sensor:
  - platform: mediarr
    plex:  # Optional
      host: 192.168.178.184
      port: 32400
      token: xxx
(It's definitly the correct token, because some Docker-Container uses the token)

    seer: # Optional
      url: http://192.168.178.102:5055
      api_key: xxx (It's the overseer token)
      max_items: 10
      tmdb_api_key: xxx (here i tried at first the "short" api, but it seems to work better with read only api)
      trending: true      
      discover: true  
      popular_movies: true  
      popular_tv: true 

    sonarr:  # Optional
      url: http://192.168.178.102:8989
      api_key: xxx
      max_items: 10
      days_to_check: 60
      tmdb_api_key: xxx

    radarr:  # Optional
      url: http://192.168.178.102:8310
      api_key: xxx
      max_items: 10
      days_to_check: 60 #breaking change
      tmdb_api_key: xxx
    
    trakt:  # Optional
      client_id: xxx
      client_secret: xxx
      tmdb_api_key: xxx
      trending_type: both  # Options: movies, shows, both
      max_items: 10
     
    
    tmdb:  # Optional
      api_key: xxx
      trending_type: all  # Options: movie, tv, all
      max_items: 10
      trending: true          # Default endpoint
      now_playing: true       # Optional
      upcoming: true          # Optional
      on_air: true            # Optional
      airing_today: false     # Optional`

**Comment by Vansmak** [comment]
Change Plex to url: like the others. No host: no port:
Add tmdb_api_key: to Plex too

Use long key for tmdb for all tmdb

I haven't used overseer so I am curious if it works so let me know.

**Comment by Vansmak** [comment]
And take tmdb out of sonarr and radarr

```
sensor:
  - platform: mediarr
    plex:  # Optional
      url: Plex url
      token: your_token
      max_items: 10
      tmdb_api_key: "your_tmdb_api_key"

    jellyfin:  # Optional
      url: jellyfin url
      token: your_api_key 
      max_items: 10
      tmdb_api_key: "your_tmdb_api_key"

    seer: # Optional #shows requests
      url: localhost
      api_key: your_api_key
      max_items: 10
      tmdb_api_key: "your_tmdb_api_key" 
      trending: true      
      discover: true  
      popular_movies: true  
      popular_tv: true 

    sonarr:  # Optional
      url: http://localhost:8989
      api_key: your_sonarr_api_key
      max_items: 10
      days_to_check: 60
     

    radarr:  # Optional
      url: http://localhost:7878
      api_key: your_radarr_api_key
      max_items: 10
      days_to_check: 60 #breaking change
      
    
    trakt:  # Optional
      client_id: "your_client_id"
      client_secret: "your_client_secret"
      tmdb_api_key: "your_tmdb_api_key"  # Required for posters
      trending_type: both  # Options: movies, shows, both
      max_items: 10
     
    
    tmdb:  # Optional
      api_key: "your_api_key"
      trending_type: all  # Options: movie, tv, all
      max_items: 10
      trending: true          # Default endpoint
      now_playing: true       # Optional
      upcoming: true          # Optional
      on_air: true            # Optional
      airing_today: false     # Optional
```
